In [3]:
import sys
import os

PROJECT_ROOT = r"c:\Projects\TEYZIX-CORE-INTERNSHIP\task-3_Telco_Churn_System"
sys.path.append(PROJECT_ROOT)

In [11]:
from src.pipeline import run_batch_scoring
print("Pipeline imported successfully ")

Pipeline imported successfully

In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [13]:
file_path = r"c:\Projects\TEYZIX-CORE-INTERNSHIP\task-3_Telco_Churn_System\dataset\raw\WA_Fn-UseC_-Telco-Customer-Churn.csv"

data = pd.read_csv(file_path)

In [14]:
data["Churn"] = data["Churn"].map({"Yes": 1, "No": 0})

data.drop(columns=["customerID"], inplace=True)

data["TotalCharges"] = pd.to_numeric(data["TotalCharges"], errors="coerce")
data["TotalCharges"].fillna(data["TotalCharges"].median(), inplace=True)

data = pd.get_dummies(data, drop_first=True)

C:\Users\10\AppData\Local\Temp\ipykernel_17932\4075300965.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["TotalCharges"].fillna(data["TotalCharges"].median(), inplace=True)

In [15]:
X = data.drop("Churn", axis=1)
y = data["Churn"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [16]:
from src.pipeline import run_batch_scoring
results = run_batch_scoring(X_test)
results.head()

,churn_probability,risk_level,recommendations
0,0.654849,MEDIUM,[Send personalized retention email campaign]
1,0.064059,LOW,"[No immediate action required, Keep customer e..."
2,0.004513,LOW,"[No immediate action required, Keep customer e..."
3,0.607217,MEDIUM,[Send personalized retention email campaign]
4,0.006364,LOW,"[No immediate action required, Keep customer e..."

In [17]:
results.head()

,churn_probability,risk_level,recommendations
0,0.654849,MEDIUM,[Send personalized retention email campaign]
1,0.064059,LOW,"[No immediate action required, Keep customer e..."
2,0.004513,LOW,"[No immediate action required, Keep customer e..."
3,0.607217,MEDIUM,[Send personalized retention email campaign]
4,0.006364,LOW,"[No immediate action required, Keep customer e..."